config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"
  get "sign-in", to: "authentication#new"
  post "sign-in", to: "authentication#create"
  get "sign-out", to: "authentication#destroy"

  resources :users, only: [] do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:index, :show]

  resources :posts  do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Thanks for signing in!"
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_logged_in

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params.merge(user_id: current_user.id))
    if @comment.save
      flash[:notice] = "Thanks for regaling us with your shitty opinions"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def ensure_logged_in
    unless current_user
      redirect_to root_path, notice: "You must log in to do that"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      flash[:notice] = "Post was created with GREAT SUCCESS"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Updated that schitt"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "BURN IT ALL"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :post_content)
  end

  def ensure_logged_in
    unless current_user
      redirect_to root_path, notice: "You must log in to do that"
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
Sign In

<%= form_tag sign_in_path do |f| %>
<%= label_tag :email %>
<%= email_field_tag :email %>
<%= label_tag :password %>
<%= password_field_tag :password %>
<%= submit_tag "Sign In"%>
<% end %>

app/views/comments/edit.html.erb
Edit Comment

<%= form_for [@post, @comment] do |c| %>
  <%= c.label :content %>
  <%= c.text_area :content %>
  <%= c.submit "My 2 Cents' Worth" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>

<% if current_user %>
  <%= link_to "Sign Out", sign_out_path %>
<% else %>
  <%= link_to "Sign In", sign_in_path %>
  <%= link_to "Sign Up", sign_up_path %>
<% end %>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :post_content %>
  <%= f.text_area :post_content %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
Edit Dat Post

<%= render "form" %>

app/views/posts/index.html.erb
Readit Main Page

<% @posts.each do |post| %>
  <%=  link_to post.title, post_path(user_id: post.user.id, id: post.id) if post.user%>
<% end %>

<% if current_user %>
  <%= link_to "New Post", new_user_post_path(current_user) %>
<% end %>

app/views/posts/new.html.erb
Add a New Post

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :post_content %>
  <%= f.text_area :post_content %>
  <%= f.submit "CREATE DAT POST" %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.post_content %><br>
<% @post.comments.each do |comment| %>
  <%= comment.content %><br>
  <% if current_user.id == comment.user_id %>
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %><br>
    <%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete %><br>
  <% end %>
<% end %>

<hr>

<% if current_user %>
  <%= form_for [@post, @comment] do |c| %>
    <%= c.label :content %>
    <%= c.text_area :content %>
    <%= c.submit "My 2 Cents' Worth" %>
  <% end %>
<% end %>

<% if current_user && current_user.id == @post.user_id %>
  <%= link_to "Edit Post", edit_post_path %>
  <%= link_to "Delete Post", post_path(@post), method: :delete %>
<% end %>